server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:commandes-db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mes-config-ms:
  commandes-last: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"

